import {products as bouquets} from './catalog-data.js';
import {addons} from './addons.js?v=benefits6';
const products=[...bouquets,...addons];
import {normalizeCart,selectProducts,total,loadCart,saveCart,validPhone,recipientLine} from './logic.js?v=benefits6';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<svg class="icon" aria-hidden="true"><use href="#${name}"/></svg>`;
const labels={author:'Авторский букет',bloom:'Bloom Edit',baskets:'Цветочная корзина'};
let storage;try{storage=window.localStorage;}catch{}
let cart=loadCart(storage,products), selected=null, toastTimer, lastFocus=null;
const find=id=>products.find(p=>p.id===id);
function toast(message){const el=$('.toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800);}
function show(dialog){for(const other of $$('dialog[open]'))other.close();lastFocus=document.activeElement;dialog.showModal();}
for(const dialog of $$('dialog')){
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 dialog.addEventListener('close',()=>{if(dialog.id==='product-dialog'){const u=new URL(location);u.searchParams.delete('product');history.replaceState(null,'',u);}if(lastFocus?.isConnected)lastFocus.focus();});
}
function resetOrderPreview(){const result=$('#order-result');if(result&&!result.hidden){result.hidden=true;$('#order-text').value='';$('#order-visual').replaceChildren();}}
function persist(){resetOrderPreview();cart=normalizeCart(cart,products);if(!saveCart(storage,cart))toast('Корзина сохранена до закрытия страницы');renderCart();}
function add(id){const p=find(id);if(!p?.price||p.addon)return;const row=cart.find(r=>r.id===id);if(row){if(row.quantity>=99){toast('Для большого заказа свяжитесь с флористом');return;}row.quantity++;}else cart.push({id,quantity:1});persist();toast('Букет добавлен в корзину');}
function card(p){return `<article class="product-card"><a class="product-image" href="catalog.html?v=benefits6&product=${encodeURIComponent(p.id)}" data-product="${p.id}"><img src="${p.images[0]}" alt="${escape(p.alt)}" width="900" height="1125" loading="lazy"><span class="view-product">Рассмотреть ${icon('arrow')}</span></a><div class="product-caption"><div><span class="product-collection">${labels[p.collection]}</span><h3><a href="catalog.html?v=benefits6&product=${encodeURIComponent(p.id)}" data-product="${p.id}">${escape(p.name)}</a></h3><span class="price">${p.price?money(p.price):'По запросу'}</span></div><button class="add-button" ${p.price?`data-add="${p.id}"`:`data-inquire="${p.id}"`} aria-label="${p.price?'В корзину':'Уточнить цену'}: ${escape(p.name)}">${icon(p.price?'bag':'arrow')}</button></div></article>`;}
function product(id){const p=find(id);if(!p||p.addon){toast('Этот букет не найден в каталоге');return;}selected=p;
 $('#product-content').innerHTML=`<div class="product-detail"><div class="detail-photo"><img id="detail-image" src="${p.images[0]}" alt="${escape(p.alt)}" width="900" height="1125"></div><div class="detail-copy"><span class="eyebrow">${labels[p.collection]}</span><h2 id="product-title">${escape(p.name)}</h2><div class="detail-price">${p.price?money(p.price):'Стоимость по запросу'}</div><p>${escape(p.description)}</p><p>Состав, размер и наличие уточним перед заказом. Цветы и оттенки могут зависеть от сезона.</p>${p.price?`<button class="button primary" data-add="${p.id}">Добавить в корзину ${icon('bag')}</button>`:`<button class="button primary" data-inquire="${p.id}">Уточнить у флориста ${icon('arrow')}</button>`}<button class="text-link" data-inquire="${p.id}">Обсудить букет с флористом ${icon('arrow')}</button><p class="fine" style="margin:18px 0 0">Доставка по Москве — от 250 ₽.<br>Самовывоз из салона — бесплатно.</p>${p.images.length>1?`<div class="detail-thumbs" aria-label="Ракурсы букета">${p.images.map((im,i)=>`<button data-image="${i}" aria-label="Ракурс ${i+1}" aria-pressed="${i===0}"><img src="${im}" alt=""></button>`).join('')}</div>`:''}</div></div>`;
 const d=$('#product-dialog');d.setAttribute('aria-labelledby','product-title');show(d);const u=new URL(location);u.searchParams.set('product',id);history.replaceState(null,'',u);
}
function cartRows(editable=true){return cart.filter(r=>!editable||!find(r.id).addon).map(r=>{const p=find(r.id);return `<div class="cart-row"><img src="${p.images[0]}" alt="${escape(p.name)}" width="80" height="100"><div><h3>${escape(p.name)}</h3>${p.addon?'<small class="demo-label">Тестовый пример · условная цена</small>':''}<p>${money(p.price)}${editable?'':` × ${r.quantity}`}</p>${editable?`<div class="cart-row-bottom"><div class="quantity"><button data-quantity="${r.id}" data-delta="-1" aria-label="Уменьшить количество: ${escape(p.name)}">−</button><span>${r.quantity}</span><button data-quantity="${r.id}" data-delta="1" ${r.quantity>=99?'disabled':''} aria-label="Увеличить количество: ${escape(p.name)}">+</button></div><button class="remove" data-remove="${r.id}">Убрать</button></div>`:''}</div></div>`;}).join('');}
function renderCart(){const t=total(cart,products);$$('[data-count]').forEach(el=>el.textContent=t.count);$('#cart-items').innerHTML=cart.length?cartRows()+upsell():`<div class="empty-state"><h2>Здесь будет<br><em>ваш букет</em></h2><p>Выберите цветы для важного человека.</p><a class="button primary" href="catalog.html?v=benefits6">Посмотреть букеты ${icon('arrow')}</a></div>`;
 $('#cart-bottom').innerHTML=cart.length?`<div class="cart-total"><span>${cart.some(r=>find(r.id).addon)?'Букет и дополнения':'Букеты'}</span><strong>${money(t.subtotal)}</strong></div><p class="fine">Доставка — на следующем шаге</p><a href="checkout.html?v=benefits6" data-checkout class="button primary">К оформлению ${icon('arrow')}</a><p class="cart-choice-note">${cart.some(r=>find(r.id).addon)?'Условные цены дополнений — только для теста':'Можно продолжить без дополнений'}</p>`:'';renderCheckout();}
function upsell(){return `<section class="upsell" aria-labelledby="upsell-title"><div class="upsell-heading"><span class="eyebrow">Последний штрих</span><h3 id="upsell-title">Дополнить <em>подарок</em></h3><p>По желанию. Ничего лишнего.</p></div><p class="upsell-demo">Пример для теста: товары и цены условные.</p><div class="upsell-grid">${addons.map(p=>{const chosen=cart.some(r=>r.id===p.id);return `<article class="upsell-card ${chosen?'chosen':''}"><img src="${p.images[0]}" width="120" height="140" alt="${escape(p.alt)}"><div><h4>${escape(p.name)}</h4><p>${escape(p.description)}</p><button data-addon="${p.id}" aria-pressed="${chosen}" aria-label="${chosen?'Убрать':'Добавить'}: ${escape(p.name)}">${chosen?'✓ Добавлено · убрать':'+ '+money(p.price)}</button></div></article>`;}).join('')}</div></section>`;}
function toggleAddon(id){if(!addons.some(p=>p.id===id)||!cart.some(r=>!find(r.id).addon))return;const chosen=cart.some(r=>r.id===id);cart=chosen?cart.filter(r=>r.id!==id):[...cart,{id,quantity:1}];persist();$(`[data-addon="${id}"]`)?.focus();toast(chosen?'Дополнение убрано':'Тестовое дополнение добавлено');}

function help(id){const p=find(id);$('#help-form').hidden=false;$('#help-result').hidden=true;$('#help-form').reset();if(p)$('[name=wishes]',$('#help-form')).value=`Интересует ${p.name}${p.price?', '+money(p.price):''}. `;show($('#help-dialog'));}
let filters={collection:'all',budget:'',search:'',sort:'curated'};
function readFilters(){const q=new URLSearchParams(location.search);filters={collection:['author','bloom','baskets'].includes(q.get('collection'))?q.get('collection'):'all',budget:['5000','10000','15000'].includes(q.get('budget'))?q.get('budget'):'',search:q.get('search')||'',sort:['price-asc','price-desc'].includes(q.get('sort'))?q.get('sort'):'curated'};}
function renderCatalog(updateUrl=true){if(!$('#catalog-grid'))return;const list=selectProducts(bouquets,filters);$('#catalog-grid').innerHTML=list.map(card).join('');$('#no-results').hidden=!!list.length;$('#result-count').textContent=`Найдено: ${list.length}`;$$('[data-collection]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.collection===filters.collection));$('#budget').value=filters.budget;$('#sort').value=filters.sort;$('#search').value=filters.search;if(updateUrl){const u=new URL(location);for(const [k,v] of Object.entries(filters))if(v&&v!=='all'&&v!=='curated')u.searchParams.set(k,v);else u.searchParams.delete(k);history.replaceState(null,'',u);}}
function resetFilters(){filters={collection:'all',budget:'',search:'',sort:'curated'};renderCatalog();}
if($('#catalog-grid')){readFilters();renderCatalog(false);$('#search').addEventListener('input',e=>{filters.search=e.target.value;renderCatalog();});for(const k of ['budget','sort'])$('#'+k).addEventListener('change',e=>{filters[k]=e.target.value;renderCatalog();});}
function mode(){return $('[name=mode]:checked')?.value||'pickup';}
function renderCheckout(){if(!$('#checkout-layout'))return;const has=cart.length>0;$('#checkout-empty').hidden=has;$('#checkout-layout').hidden=!has||!$('#order-result').hidden;$('#checkout-items').innerHTML=cartRows(false);const t=total(cart,products,mode());$('#checkout-total').innerHTML=`<div class="totals-line"><span>Букет${cart.some(r=>find(r.id).addon)?' и дополнения':'ы'}</span><span>${money(t.subtotal)}</span></div><div class="totals-line"><span>${mode()==='pickup'?'Самовывоз':'Доставка'}</span><span>${t.delivery?money(t.delivery):'Бесплатно'}</span></div><div class="totals-line final"><span>Итого</span><strong>${money(t.total)}</strong></div><p class="fine">Наличие букета и время подтвердит флорист.</p>`;}
const checkout=$('#checkout-form');
if(checkout){for(const input of $$('input[type=tel]',checkout)){const check=()=>input.setCustomValidity(input.value&&!validPhone(input.value)?'Введите номер телефона: от 10 до 15 цифр':'');input.addEventListener('input',check);input.addEventListener('change',check);}const date=$('[name=date]',checkout);const now=new Date();date.min=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 checkout.addEventListener('change',e=>{if(e.target.name==='mode'){const pickup=mode()==='pickup';$('#address-label').hidden=pickup;$('#store-label').hidden=!pickup;$('[name=address]',checkout).required=!pickup;renderCheckout();}});
 checkout.addEventListener('submit',e=>{e.preventDefault();if(!cart.length||!checkout.reportValidity())return;const f=Object.fromEntries(new FormData(checkout));const t=total(cart,products,f.mode);const lines=['КЛЮЧ — предварительный заказ (не отправлен)','',...cart.map(r=>`${find(r.id).name}${find(r.id).addon?' (тестовый пример, условная цена)':''} × ${r.quantity} — ${money(find(r.id).price*r.quantity)}`),'',`Товары: ${money(t.subtotal)}`,`${f.mode==='pickup'?'Самовывоз':'Доставка'}: ${money(t.delivery)}`,`Итого: ${money(t.total)}`,'',`Заказчик: ${f.name}, ${f.phone}`,f.email?`Email: ${f.email}`:'',`${f.mode==='pickup'?'Салон':'Адрес'}: ${f.mode==='pickup'?f.store:f.address}`,`Дата: ${f.date.split('-').reverse().join('.')}`,`Время: ${f.slot}`,recipientLine(f),f.message?`Открытка: ${f.message}`:'',f.wishes?`Пожелания: ${f.wishes}`:''];$('#order-text').value=lines.filter(Boolean).join('\n');
 const detail=(label,value)=>value?`<div><dt>${label}</dt><dd>${escape(value)}</dd></div>`:'';
 $('#order-visual').innerHTML=`<div class="order-review"><section class="order-review-products" aria-label="Состав заказа"><span class="eyebrow">Ваш выбор</span>${cartRows(false)}<div class="review-total"><span>Товары</span><strong>${money(t.subtotal)}</strong></div><div class="review-total"><span>${f.mode==='pickup'?'Самовывоз':'Доставка'}</span><strong>${t.delivery?money(t.delivery):'Бесплатно'}</strong></div><div class="review-total review-grand"><span>Итого</span><strong>${money(t.total)}</strong></div></section><section class="order-review-details" aria-label="Детали получения"><span class="eyebrow">Для важного человека</span><h3>${f.mode==='pickup'?'Встретимся в салоне':'Передадим лично'}</h3><dl>${detail('Заказчик',f.name)}${detail('Телефон',f.phone)}${detail('Email',f.email)}${detail(f.mode==='pickup'?'Салон':'Адрес',f.mode==='pickup'?f.store:f.address)}${detail('Дата и время',f.date.split('-').reverse().join('.')+' · '+f.slot)}${detail('Получатель',[f.recipient,f.recipientPhone].filter(Boolean).join(', '))}${detail('Слова для открытки',f.message)}${detail('Пожелания',f.wishes)}</dl><p class="fine">Это предварительный просмотр. Заказ ещё не отправлен.</p></section></div>`;$('#checkout-layout').hidden=true;$('#order-result').hidden=false;$('#order-result').focus();$('#order-result').scrollIntoView({behavior:'smooth',block:'start'});});
 $('#edit-order').addEventListener('click',()=>{$('#order-result').hidden=true;renderCheckout();checkout.scrollIntoView({behavior:'smooth'});});
}
$('#help-form').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));$('#help-text').value=`Здравствуйте! Помогите подобрать букет.\nПовод: ${f.occasion}.\nБюджет: ${f.budget}.\n${f.wishes?'Пожелания: '+f.wishes+'\n':''}${cart.length?'В корзине: '+cart.map(r=>find(r.id).name+(find(r.id).addon?' (тестовый пример)':'')+' × '+r.quantity).join(', ')+'.':''}`;e.target.hidden=true;$('#help-result').hidden=false;$('#help-text').focus();});
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;
 if(b.hasAttribute('data-close'))b.closest('dialog').close();
 else if(b.hasAttribute('data-product')){e.preventDefault();product(b.dataset.product);}
 else if(b.hasAttribute('data-add')){add(b.dataset.add);}
 else if(b.hasAttribute('data-addon'))toggleAddon(b.dataset.addon);
 else if(b.hasAttribute('data-checkout')&&checkout){e.preventDefault();$('#cart-dialog').close();renderCheckout();const target=$('#order-result').hidden?checkout:$('#order-result');target.scrollIntoView({behavior:'smooth',block:'start'});$('input',target)?.focus({preventScroll:true});}
 else if(b.hasAttribute('data-cart'))show($('#cart-dialog'));
 else if(b.hasAttribute('data-help')||b.hasAttribute('data-inquire'))help(b.dataset.inquire);
 else if(b.hasAttribute('data-remove')){cart=cart.filter(r=>r.id!==b.dataset.remove);persist();$('#cart-items button, #cart-items a, #cart-dialog [data-close]')?.focus();}
 else if(b.hasAttribute('data-quantity')){const r=cart.find(r=>r.id===b.dataset.quantity);if(r){const id=r.id,delta=b.dataset.delta;r.quantity+=Number(delta);persist();const target=$(`[data-quantity="${id}"][data-delta="${delta}"]:not(:disabled)`);(target||$('#cart-items button, #cart-items a, #cart-dialog [data-close]'))?.focus();}}
 else if(b.hasAttribute('data-image')&&selected){const i=Number(b.dataset.image);$('#detail-image').src=selected.images[i];$$('[data-image]').forEach(el=>el.setAttribute('aria-pressed',el===b));}
 else if(b.hasAttribute('data-collection')){filters.collection=b.dataset.collection;renderCatalog();}
 else if(b.id==='reset-filters'||b.hasAttribute('data-reset'))resetFilters();
 else if(b.hasAttribute('data-menu')){const menu=$('.mobile-menu');menu.style.top=$('.header').getBoundingClientRect().bottom+'px';menu.hidden=!menu.hidden;b.setAttribute('aria-expanded',!menu.hidden);}
 else if(b.hasAttribute('data-copy')){const area=$('#'+b.dataset.copy);try{await navigator.clipboard.writeText(area.value);toast('Текст скопирован');}catch{const details=area.closest('details');if(details)details.open=true;area.focus();area.select();toast('Выделили текст — скопируйте его вручную');}}
 if(b.closest('.mobile-menu')&&(b.tagName==='A'||b.hasAttribute('data-help'))){$('.mobile-menu').hidden=true;$('[data-menu]').setAttribute('aria-expanded','false');}
});
window.addEventListener('storage',e=>{if(e.key==='klyuch-preview-cart-v1'){resetOrderPreview();cart=loadCart(storage,products);renderCart();}});
window.addEventListener('popstate',()=>{readFilters();renderCatalog(false);const id=new URLSearchParams(location.search).get('product');if(id)product(id);else $('#product-dialog').close();});
renderCart();const productId=new URLSearchParams(location.search).get('product');if(productId)product(productId);
if($('#info-content')){
 const page=new URLSearchParams(location.search).get('page');const texts={care:`<p class="eyebrow">Чтобы радовал дольше</p><h1>Забота о <em>букете</em></h1><div class="prose"><p>У разных цветов свои особенности. Флорист подскажет уход именно за вашим букетом.</p><h2>Начните с чистой вазы</h2><p>Обновите срезы и уберите листья, которые окажутся в воде. Используйте чистую прохладную воду и подходящую подкормку по инструкции.</p><h2>Найдите спокойное место</h2><p>Избегайте прямого солнца, батарей и сквозняков. Не ставьте букет рядом с созревающими фруктами.</p><h2>Обновляйте воду</h2><p>Следите за её чистотой и уровнем, удаляйте увядшие цветы. Композиции в корзинах требуют другого ухода — уточните его при получении.</p></div>`,services:`<p class="eyebrow">Для ваших особенных дней</p><h1>Больше, чем <em>букет</em></h1><div class="prose"><p>Цветы для свадьбы, праздника, события или пространства. Обсудите с флористом идею, дату, палитру и бюджет.</p><button class="button primary" data-help>Обсудить оформление ${icon('arrow')}</button><h2>Цветы для бизнеса</h2><p>Подарки коллегам и партнёрам, оформление мероприятий и регулярные букеты. Состав услуги и стоимость согласовываются индивидуально.</p></div>`,documents:`<p class="eyebrow">Открыто о важном</p><h1>Информация <em>для покупателя</em></h1><div class="prose"><p>Вы на тестовой версии: она не принимает оплату и не отправляет введённые в форму данные. Корзина хранится только в вашем браузере.</p><p>Для действующих условий покупки перейдите к документам текущего магазина. Перед запуском новой версии их необходимо проверить и актуализировать.</p><div class="document-links"><a href="https://klyuch.store/offer.html" target="_blank" rel="noopener">Публичная оферта ↗</a><a href="privacy.html?v=benefits6">Политика конфиденциальности</a><a href="https://klyuch.store/delivery-returns.html" target="_blank" rel="noopener">Доставка и возврат ↗</a><a href="https://klyuch.store/seller-details.html" target="_blank" rel="noopener">Реквизиты продавца ↗</a></div></div>`};
 if(texts[page])$('#info-content').innerHTML=texts[page];
}

// Forms are inert until all local-only handlers are installed.
$$('[data-init-disabled]').forEach(el=>{el.disabled=false;el.removeAttribute('data-init-disabled');});
$$('[data-init-notice]').forEach(el=>el.hidden=true);
